---
  - hosts: localhost
    connection: local
    vars:
      - miniconda_prefix: "/opt/miniconda3"
    tasks:
      - name: Setup git
        apt:
          name: git
          state: latest

      - name: Setup vim
        apt:
          name: vim
          state: latest

    roles:
      - role: angstwad.docker_ubuntu
        uninstall_previous_docker_versions: true
        start_docker_daemon: no
        tags:
          - docker

      - role: uchida.miniconda
        miniconda_version: latest
        tags:
          - conda

    post_tasks:
      - name: Add to bashrc, the docker daemon IP connection
        lineinfile:
          path: ~/.bashrc
          line: 'export DOCKER_HOST=tcp://192.168.0.144:2375'
        tags:
          - docker

      - name: add {{ miniconda_prefix }} to a global path
        lineinfile: >
          dest=/etc/environment
          state=present
          backrefs=yes
          regexp='PATH=(["]*)((?!.*?{{miniconda_prefix}}/bin).*?)(["]*)$'
          line="PATH=\1\2:{{miniconda_prefix}}/bin\3"
        tags:
          - conda
